title: Igor Santana
logo: /assets/img/profile.png
description: Desenvolvedor Frontend | React Developer | JavaScript Developer | HTML | CSS
show_downloads: false
theme: jekyll-theme-minimal

# Informações de contato (usando HTML personalizado)
contact_info: |
  <p><img src="{{ '/assets/img/phone.svg' | relative_url }}" alt="Telefone" class="contact-icon"> <a href="tel:+5511985716194">(11) 98571-6194</a></p>
  <p><img src="{{ '/assets/img/email.svg' | relative_url }}" alt="Email" class="contact-icon"> <a href="mailto:santanna.ig@hotmail.com">santanna.ig@hotmail.com</a></p>
  <p><img src="{{ '/assets/img/linkedin.svg' | relative_url }}" alt="LinkedIn" class="contact-icon"> <a href="https://www.linkedin.com/in/igor-santana-6b3192136" target="_blank">LinkedIn</a></p>
  <p><img src="{{ '/assets/img/github.svg' | relative_url }}" alt="GitHub" class="contact-icon"> <a href="https://github.com/tligor" target="_blank">GitHub</a></p>

# Projetos
projects:
  - name: Clone Disney+
    url: https://clone-disneyplus-delta-one.vercel.app/
    repo: https://github.com/tligor/clone_disneyplus/tree/main
  - name: Tech Talks
    url: https://tech-talks-woad.vercel.app/
    repo: https://github.com/tligor/Tec_talks

# Habilidades técnicas
skills:
  - React
  - JavaScript
  - HTML
  - CSS
  - Git
  - Node.js
  - TypeScript
  - Vue.js
  - Bootstrap
  - Redux
  - APIs REST
  - Spring Boot
  - Java

# SEO
meta:
  description: "Portfólio de Igor Santana, Desenvolvedor Frontend com experiência em React, JavaScript, HTML e CSS."
  keywords: "Desenvolvedor Frontend, React, JavaScript, HTML, CSS, Portfólio"
