title: Igor Santana
logo: /assets/img/profile.png
description: Desenvolvedor Frontend | React Developer | JavaScript Developer | HTML | CSS
show_downloads: false
theme: jekyll-theme-minimal
email: santanna.ig@hotmail.com
linkedin: https://www.linkedin.com/in/igor-santana-6b3192136
