title: Igor Santana
baseurl: "/portfolio"
logo: /assets/img/profile.png
description: Desenvolvedor Frontend | React Developer | JavaScript Developer | HTML | CSS
show_downloads: false
theme: jekyll-theme-minimal

# Informações de contato (usando HTML personalizado)
contact_info: |
  <p style="display: flex; align-items: center; margin: 10px 0;">
    <img src="https://raw.githubusercontent.com/tligor/portfolio/main/assets/img/phone.svg" alt="Telefone" style="width: 16px; height: 16px; margin-right: 10px;">
    <a href="tel:+5511985716194" style="color: #0366d6; text-decoration: none;">(11) 98571-6194</a>
  </p>
  <p style="display: flex; align-items: center; margin: 10px 0;">
    <img src="https://raw.githubusercontent.com/tligor/portfolio/main/assets/img/email.svg" alt="Email" style="width: 16px; height: 16px; margin-right: 10px;">
    <a href="mailto:santanna.ig@hotmail.com" style="color: #0366d6; text-decoration: none;">santanna.ig@hotmail.com</a>
  </p>
  <p style="display: flex; align-items: center; margin: 10px 0;">
    <img src="https://raw.githubusercontent.com/tligor/portfolio/main/assets/img/linkedin.svg" alt="LinkedIn" style="width: 16px; height: 16px; margin-right: 10px;">
    <a href="https://www.linkedin.com/in/igor-santana-6b3192136" target="_blank" style="color: #0366d6; text-decoration: none;">LinkedIn</a>
  </p>
  <p style="display: flex; align-items: center; margin: 10px 0;">
    <img src="https://raw.githubusercontent.com/tligor/portfolio/main/assets/img/github.svg" alt="GitHub" style="width: 16px; height: 16px; margin-right: 10px;">
    <a href="https://github.com/tligor" target="_blank" style="color: #0366d6; text-decoration: none;">GitHub</a>
  </p>
  
# Projetos
projects:
  - name: Clone Disney+
    url: https://clone-disneyplus-delta-one.vercel.app/
    repo: https://github.com/tligor/clone_disneyplus/tree/main
  - name: Tech Talks
    url: https://tech-talks-woad.vercel.app/
    repo: https://github.com/tligor/Tec_talks

# Habilidades técnicas
skills:
  - React
  - JavaScript
  - HTML
  - CSS
  - Git
  - Node.js
  - TypeScript
  - Vue.js
  - Bootstrap
  - Redux
  - APIs REST
  - Spring Boot
  - Java

# SEO
meta:
  description: "Portfólio de Igor Santana, Desenvolvedor Frontend com experiência em React, JavaScript, HTML e CSS."
  keywords: "Desenvolvedor Frontend, React, JavaScript, HTML, CSS, Portfólio"
